database:
  name: test
  host: "127.0.0.1"
  port: 3306
  user: root
  pass: 123456

enccryptokey: "12345678901234567890123456789012"

jwt:
  secret: this_is_a_secret_sample

rdkit:
  python_path: python

static: false
adress_port: ":9090"